### ISSUE TITLE
KRouterLink should provide a way to render its KIcon (via `icon` prop) without styling

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri-design-system#135]
Providing an `icon` prop to `KRouterLink` like this

https://github.com/learningequality/kolibri/blob/68f33c3f429f55c60af23d6752ba389a6ac20a0d/kolibri/plugins/device/assets/src/views/DeviceSettingsPage/index.vue#L90-L95

ends up with a link like this ([link](https://kolibri-beta.learningequality.org/ko/device/#/settings)):

![image](https://user-images.githubusercontent.com/10248067/99467828-0b33af80-28f4-11eb-9ec9-6319190cf31a.png)

Where, the icon is clickable and styled like and the link (same color, etc.)

I think the more common usage is more like this ([link](https://kolibri-beta.learningequality.org/ko/facility/#/facilities)):

![image](https://user-images.githubusercontent.com/10248067/99467885-2dc5c880-28f4-11eb-8915-bc45c8a615a5.png)

Which is achieved with this code:

https://github.com/learningequality/kolibri/blob/68f33c3f429f55c60af23d6752ba389a6ac20a0d/kolibri/plugins/coach/assets/src/views/AllFacilitiesPage.vue#L23-L29

Where the icon is pre-pended to the link and is not part of the anchor tag. 

The ability to do something like the AllFacilitiesPage style of link using only a single `KRouterLink` component might be convenient.

**Comment by indirectlylit** [comment]
We'll also want to update our generalized guidance on the matter. Here's what we currently have:

https://kolibri-design-system.netlify.app/icons/#color

> <img width="790" alt="image" src="https://user-images.githubusercontent.com/2367265/99473860-4f2cb180-2900-11eb-843e-9f4ee29f1fa9.png">

We can update this to be more specific about different contexts like links, labeled icons, etc.

**Comment by sairina** [comment]
Hey @jb and @indirectlylit, I just want to make sure I'm understanding the issue before I start working on it! The goal would be to make the `icon` prop in `KRouterLink` produce something that looks like the middle picture instead of its current form (the picture on the right)?

From my understanding, the two images in this issue are from two different components, BUT when I use the `icon` prop that's in `KRouterLink`, it does render something that looks like `KExternalLink`:
|`KExternalLink`|`KRouterLink`|`KRouterLink` with `icon`|
|--|--|--|
|![image](https://user-images.githubusercontent.com/10248067/99467828-0b33af80-28f4-11eb-9ec9-6319190cf31a.png)|![image](https://user-images.githubusercontent.com/10248067/99467885-2dc5c880-28f4-11eb-8915-bc45c8a615a5.png)|![Screen Shot 2021-02-03 at 10 03 33 PM](https://user-images.githubusercontent.com/13563002/106851855-d4a44000-666b-11eb-902d-e5a1e2896c3f.png)|

**Comment by indirectlylit** [comment]
Hey, a few comments here.

### Relationship between various components

`KExternalLink`, `KRouterLink`, and `KButton` should all visually behave the same, and where possible props should result in the same behaviors. See [https://design-system.learningequality.org/buttons/](https://design-system.learningequality.org/buttons/) for more info.

The `icon` prop in particular should definitely have the same behavior across all components.

The main difference between these components is that they generate `<a>`, `<router-link>`, and `<button>` tags respectively. Any changes and decisions we make should apply consistently to all components in this group.

### Standardizing behavior versus adding more settings

The most common issue we encounter with the design system is how to handle special cases. The two basic strategies are:

1. Add more rules or settings to permit flexibility
2. Remove special cases and standardize

See [design-system.learningequality.org/#exceptions](https://design-system.learningequality.org/#exceptions) for more info. We should start this issueas a design question before making technical component API decisions.

In this case, we have a scenario where a common usage is to prepend an icon before a link, but make the icon _not_ actually part of the link. As far as I know, this only happens in tables.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/2367265/106932721-ebc74a00-66cc-11eb-963f-4e368a8ca878.png">

Before adding a new prop to our button components to handle the table special case, I think we should ask why _isn't_ the icon clickable and part of the link?  Is there anything wrong with doing it this way?

![image](https://user-images.githubusercontent.com/2367265/106932831-0dc0cc80-66cd-11eb-9ccb-0df21afb9fd5.png)

If this is fine, then let's simply standardize on that behavior rather than making the design system component more complicated. At the moment, this is my impression – it's simpler to use the same behavior everywhere.

### Is the special behavior worth it?

If we do in fact want to keep this special behavior in our designs where icons next to links in tables are not clickable, does it actually make sense to add this to the `KExternalLink`, `KRouterLink`, and `KButton` components? 

Compare the current code:

```vue
<KLabeledIcon icon="facility">
  <KRouterLink
    :text="facility.name"
    :to="coachClassListPageLink(facility)"
  />
</KLabeledIcon>
```

with a possible update:

```vue
<KRouterLink
  :text="facility.name"
  :to="coachClassListPageLink(facility)"
  icon="facility"
  linkedIcon="false"
/>
```

They're the same number of lines, but we've added extra complexity to the API of the link component. It's not clear to me that much is gained.

**Comment by jtamiace** [comment]
Just want to make sure i’m understanding the proposal in the last comment - making icons also clickable and part of links in tables will result in more consistent and simpler code for `KExternalLink`, `KRouterLink`, and `KButton` components?

> I think we should ask why _isn't_ the icon clickable and part of the link?

I don’t remember why we designed icons to not be clickable in tables. @khangmach do you? 

> Is there anything wrong with doing it this way:

It’s hard to imagine any significant or minor downsides to the UX in making it the norm for icons to also be clickable in tables. And, it helps that this would be pretty self-contained to tables in the learning platform (I quickly checked across KDP and Studio too). So if there are bigger gains for the dev experience, I'd be open to this change.

**Comment by khangmach** [comment]
@jtamiace I don't recall strong reasons but I do remember there were spacing and alignment issues with getting both icon and link to be vertically aligned inside of the row. Maybe this had something to do with the icon padding not meshing with the link when put together.

**Comment by indirectlylit** [comment]
> making icons also clickable and part of links in tables will result in more consistent and simpler code

Correct. Concretely, code that looks like this:

```vue
<KLabeledIcon icon="facility">
  <KRouterLink
    :text="facility.name"
    :to="coachClassListPageLink(facility)"
  />
</KLabeledIcon>
```

could be replaced with simply:

```vue
<KRouterLink
  :text="facility.name"
  :to="coachClassListPageLink(facility)"
  icon="facility"
/>
```

> spacing and alignment issues

Yes, definitely want to make sure these details work in practice before finalizing

**Comment by sairina** [comment]
This is a great discussion, all! 

So, just to make sure I've got it... it sounds like we want the **default** to be the icon in purple and clickable (with fixed spacing, of course), looking something like this:
![Screen Shot 2021-02-03 at 10 03 33 PM](https://user-images.githubusercontent.com/13563002/106851855-d4a44000-666b-11eb-902d-e5a1e2896c3f.png)

And the **option** to have the icon in black, but also clickable, which would be useful in instances where we have a `KRouterLink` in a table, which would look something like this: ![image](https://user-images.githubusercontent.com/10248067/99467885-2dc5c880-28f4-11eb-8915-bc45c8a615a5.png)

Is this correct, everyone? And, @jb, from your perspective, would having these meet the needs that you were looking for in this particular issue?

**Comment by indirectlylit** [comment]
Actually no – I was proposing that we do _not_ add the new option, and instead update Kolibri to use the purple clickable icons everywhere.

**Comment by jb** [comment]
Personally, I'd just ship it

**Comment by sairina** [comment]
Okay team - @khangmach @jtamiace @indirectlylit @jonboiser - I have a PR ready to go that gives us the use of the purple icons (clickable) via `icon` and `iconAfter` props, and should be spaced correctly in tables.

![Screen Shot 2021-02-08 at 9 22 11 PM](https://user-images.githubusercontent.com/13563002/107321279-1d3a6f80-6a57-11eb-98b7-265a9c683add.png)

Is this what we're going for?

**Comment by indirectlylit** [comment]
that implementation looks great to me – though hopefully we never use the same icon before and after in practice 😆 I'll let others confirm in but at this point I agree with our new friend: ship it!

**Comment by khangmach** [comment]
Wait, I thought the proposal was to do the following:
![image](https://user-images.githubusercontent.com/25045166/107465298-f479af00-6b16-11eb-854f-e5cec784cc40.png)

Why are there two icons? One before the title and one after?

**Comment by sairina** [comment]
You're right - that was just a quick screenshot of using both `icon` and `iconAfter` at the same time (to show spacing), but yes, it would only show the icon on the left side or on the right side of the text 😄 .

**Comment by khangmach** [comment]
Awesome, thank you. I also think it would be great to make the click area for icon + link text as one click area instead of two. This would help tie the two elements closer together and leave no confusion as to why the icon has one hover state and the link, another.

**Comment by sairina** [comment]
Hmm, @khangmach, can you show me what that would look like? 

Here's what I've seen when I tab through things, but I'm not sure this is what you're talking about:
![2021-02-10 10 32 27](https://user-images.githubusercontent.com/13563002/107554935-6ee41680-6b8b-11eb-971d-0b01d14cd1f7.gif)

**Comment by khangmach** [comment]
Basically this space in between should also be clickable, and there shouldn't be a gap where the cursor changes to a pointy cursor that indicates a non-clickable area

![clickable area](https://user-images.githubusercontent.com/25045166/107582653-a7e1b280-6bae-11eb-895c-e09576902007.png)
