### ISSUE TITLE
deprecate 'tune' alias

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri-design-system#269]
## Product

Need to check for all instances

## Desired behavior

We should rename all instances of `tune` to `settings` and deprecate the old alias:

https://design-system.learningequality.org/icons/#token-tune

## Current behavior

The icon we use for 'settings' is currently called 'tune' based on the Material name.

## (Optional) The Value Add

We should use KDS-specific naming to help engineers and designers reuse icons correctly.

**Comment by nucleogenesis** [comment]
General guidance for this is to grep the whole code base of Kolibri, Studio and KDP to ensure that there is no use of the `tune` icon and to replace it w/ the `settings` icon as noted here.

**Comment by nucleogenesis** [comment]
@nikkuAg or @sivangbagri -- if one of you'd like to take this on it seems that the only instance of this being used in Kolibri is in the epub_viewer's "SettingsButton.vue" file.

That said, fixing this will require two parts:

1: Update Kolibri to use `settings` there instead of `tune` and make a PR against Kolibri.
2: Update the Kolibri Design System `iconDefinitions.js` file to no longer include the `tune` icon, as it will no longer be used. Then make a PR on Kolibri Design System for that change

**Comment by MisRob** [comment]
Closing because we have one another `settings` icon so `tune` can't be renamed to `settings`.
