### ISSUE TITLE
KLabeledIcon (?) labels and icons overlap in RTL

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri-design-system#81]
Not sure if this is actually from KLabeledIcon, but here are some screenshots of text + icon overlapping in RTL

https://kolibri-beta.learningequality.org/ar/learn/#/topics/c/544c345f9d6c4b90a4f51c56d95243fe

![image](https://user-images.githubusercontent.com/10248067/88228894-b4a7b480-cc24-11ea-8171-b6433e9a1a7b.png)

Side Nav

![image](https://user-images.githubusercontent.com/10248067/88228914-bcffef80-cc24-11ea-82a6-4fc88614ed57.png)

**Comment by radinamatic** [comment]
Ugh, dropped the ball totally on this one, I thought I've reported it last week, but now I see I did not.

These are from Beta9, but the issue is still present on Beta13 on Windows, all 3 browsers. 

![Win7 (new start)  Running  - Oracle VM VirtualBox_778](https://user-images.githubusercontent.com/1457929/88229696-71276780-cc71-11ea-8394-acee201960e2.png)
![Win7 (new start)  Running  - Oracle VM VirtualBox_779](https://user-images.githubusercontent.com/1457929/88229698-72589480-cc71-11ea-860d-c7cd670f0752.png)
